### ISSUE TITLE
Cannot find module 'ember-cli-version-checker'

### ISSUE THREAD

**Issue by axyxnz** [yapplabs/ember-modal-dialog#196]
Has anybody encountered this error when building Ember project?

```
$ ember build --environment=production
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Building
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gitlab-runner/builds/f5821623/0/lorem-ipsum-project/web-app-v5/node_modules/ember-modal-dialog/config/environment.js:4:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
ERROR: Build failed: exit status 1
```

**package.json**

```
{
  "name": "lorem-ipsum",
  "version": "0.0.0",
  "description": "Small description for lorem-ipsum goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.10.0",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-mirage": "0.2.5",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "6.0.0",
    "ember-cli-selectize": "0.5.12",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-math-helpers": "2.0.6",
    "ember-modal-dialog": "2.2.0",
    "ember-resolver": "^2.0.3",
    "ember-tether": "0.4.0",
    "ember-wormhole": "0.5.1",
    "loader.js": "^4.0.10"
  },
  "engines": {
    "node": ">= 0.12.0"
  },
  "private": true
}
```

**Comment by k3n** [comment]
Getting this too.

**Comment by k3n** [comment]
Looks like it should be resolved by #222.

@lukemelia any word on the next release? This would be nice as it's breaking builds currently.

**Comment by lukemelia** [comment]
Just release 2.4.0 with this change.

**Comment by axyxnz** [comment]
Thanks!
