### ISSUE TITLE
Error during build in CI

### ISSUE THREAD

**Issue by sly7-7** [yapplabs/ember-modal-dialog#268]
When I `ember test` in CI, I encounter this error:

```
Environment: test
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Filter
[API] Warning: Plugin uses .read/.rebuild API: Filter
cleaning up
cleaning up...

Build Error (broccoli-persistent-filter:Babel > [Babel: ember-modal-dialog]) in ember-modal-dialog/components/basic-dialog.js

Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```

To complete, a coworker updated his working copy, and encountered
```
=================================================================================

ENV Summary:

  TIME: Thu Nov 15 2018 14:49:42 GMT+0100 (CET)
  TITLE: ember
  ARGV:
  - /Users/xxx/.nvm/versions/node/v8.9.4/bin/node
  - /Users/xxx/.nvm/versions/node/v8.9.4xxx/bin/ember
  - s
  EXEC_PATH: /Users/xxx/.nvm/versions/node/v8.9.4/bin/node
  TMPDIR: /var/folders/78/t5nljwt947gbk_l452p0zbd40000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/xxx/.rvm/gems/ruby-2.3.3/bin
  - /Users/xxx/.rvm/gems/ruby-2.3.3@global/bin
  - /Users/xxx/.rvm/rubies/ruby-2.3.3/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/xxx/.rvm/gems/ruby-2.3.3/bin
  - /Users/xxx/.rvm/gems/ruby-2.3.3@global/bin
  - /Users/xxx/.rvm/rubies/ruby-2.3.3/bin
  - /usr/local/opt/gettext/bin
  - /Users/xxx/.nvm/versions/node/v8.9.4/bin
  - /Users/xxx/.rvm/bin
  - /usr/local/Cellar/elasticsearch@1.7.6/1.7.6_1/bin
  - /Users/xxx/.rvm/bin
  - /usr/local/Cellar/elasticsearch@1.7.6/1.7.6_1/bin
  PLATFORM: darwin x64
  FREEMEM: 1774903296
  TOTALMEM: 17179869184
  UPTIME: 2564
  LOADAVG: 4.89794921875,2.91943359375,3.10888671875
  CPUS:
  - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz - 3000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.4
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/xxx/work/git/xxx/frontend/node_modules/ember-data-factory-guy/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
  - codeFrame: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-modal-dialog]` plugin. 💥
Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-modal-dialog/components/basic-dialog.js
    - line: [undefined]
    - treeDir: /Users/xxx/work/git/xxx/frontend/tmp/broccoli_persistent_filterbabel__babel_ember_modal_dialog-input_base_path-dDkAV7Iy.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-modal-dialog]` plugin. 💥
Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - name: Error
  - nodeAnnotation: Babel: ember-modal-dialog
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-modal-dialog]
  - originalErrorMessage: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - stack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/xxx/work/git/xxx/frontend/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/xxx/work/git/xxx/frontend/node_modules/ember-data-factory-guy/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)

=================================================================================
```
Then he rebuilds a second time and it worked

**Comment by rwjblue** [comment]
Was the version published with `isDevelopingAddon` set to true?

**Comment by lukemelia** [comment]
@rwjblue checked and confirmed that is was not.

**Comment by sly7-7** [comment]
Thank to both of you taking time for your comments.
I now reproduce it locally after updating to ember-cli 3.5 (my CI docker image was on 3.5 without knowing it...) I continue to investigate, maybe some other addons/dependencies conflicts. So for now I guess this 'issue' is not a bug with ember-modal-dialog. But to confirm I have first to solve the waring above. Who knows, maybe all will be resolve by itself.

**Comment by rwjblue** [comment]
The warning is from ember-cli-deprecation-workflow and is fixed in a newer major version.

**Comment by rwjblue** [comment]
OK! I have found more information, but am still digging a bit...

**Comment by sly7-7** [comment]
@rwjblue I will be back to work on December, 17th, half-time only, so I will try again and bring you news as I can. Thank you anyway

**Comment by sly7-7** [comment]
Well, after making some "magic", I don't even know if it's related, but I've updated other libs, and now the build seems ok.
Here is my package.json, maybe it could help. For me we could close this issue.

```
"devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.7.0",
    "@html-next/vertical-collection": "html-next/vertical-collection#master",
    "active-model-adapter": "^2.1.1",
    "broccoli-asset-rev": "^3.0.0",
    "chai-dom": "^1.8.0",
    "ember-ajax": "^4.0.0",
    "ember-array-contains-helper": "^2.0.0",
    "ember-async-await-helper": "^0.2.0",
    "ember-auto-import": "^1.2.15",
    "ember-cli": "~3.5.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.1.3",
    "ember-cli-chai": "^0.5.0",
    "ember-cli-code-coverage": "1.0.0-beta.4",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-deploy": "^1.0.1",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-display-revisions": "^1.0.0",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-scp": "^1.0.12",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-favicon": "^1.0.0",
    "ember-cli-flash": "^1.5.0",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^2.0.0",
    "ember-cli-inject-live-reload": "^2.0.1",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-sass": "^7.1.4",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^0.7.6",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.5.0",
    "ember-data-factory-guy": "^3.4.0",
    "ember-export-application-global": "^2.0.0",
    "ember-fetch": "^6.1.0",
    "ember-intl": "^3.5.0",
    "ember-keyboard": "^4.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-math-helpers": "^2.4.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-metrics": "poteto/ember-metrics#master",
    "ember-mocha": "^0.14.0-beta.1",
    "ember-modal-dialog": "^3.0.0-beta.2",
    "ember-moment": "^7.7.0",
    "ember-power-select": "^2.0.2",
    "ember-power-select-typeahead": "^0.7.0",
    "ember-radio-button": "^1.2.4",
    "ember-resolver": "^5.0.1",
    "ember-route-action-helper": "^2.0.6",
    "ember-simple-auth": "^1.7.0",
    "ember-sinon": "^3.0.0",
    "ember-source": "~3.5.1",
    "ember-svg-jar": "^1.2.2",
    "ember-test-selectors": "^2.0.0",
    "ember-tether": "^1.0.0-beta.2",
    "ember-uploader": "^2.0.0",
    "eslint-plugin-ember": "^5.2.0",
    "glob": "^7.1.3",
    "loader.js": "^4.7.0",
    "moment-range": "^4.0.1",
    "morgan": "^1.3.2",
    "sass": "^1.15.0"
  },
  "engines": {
    "node": "6.* || 8.* || >= 10.*"
  },
  "dependencies": {
    "d3": "^5.7.0",
    "d3-beeswarm": "^0.0.5",
    "d3-cloud": "^1.2.4",
    "file-saver": "^2.0.0",
    "hint.css": "2.2.1",
    "html-hint": "^0.2.4",
    "interactjs": "1.4.0-alpha.0",
    "ladda": "^2.0.1",
    "materialize-css": "1.0.0",
    "nouislider": "^12.1.0"
  }
```

**Comment by sly7-7** [comment]
@backspace Thanks for pointing this. So I'm closing this one.
