### ISSUE TITLE
Breaks in Ember 3.22

### ISSUE THREAD

**Issue by jacobq** [yapplabs/ember-modal-dialog#312]
Related to https://github.com/emberjs/ember.js/issues/19110

Reproduction steps: run `ember try:one ember-release` and observe multiple test failures like the one shown below:

```
not ok 40 Chrome 86.0 - [1261 ms] - Acceptance: modal-dialog | tethered and animatable: target - element
    ---
        actual: >
            [object Object]
        stack: >
            Error: Assertion Failed: You attempted to update `nodes` on `<EmberObject:ember910>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

            `nodes` was first used:

            - While rendering:
              application
                tethered-animatable

            Stack trace for the update:
                at dirtyTagFor (http://localhost:7357/assets/vendor.js:66094:9)
                at markObjectAsDirty (http://localhost:7357/assets/vendor.js:24611:32)
                at notifyPropertyChange (http://localhost:7357/assets/vendor.js:24649:5)
                at set (http://localhost:7357/assets/vendor.js:25596:9)
                at EmberObject.set (http://localhost:7357/assets/vendor.js:38776:29)
                at Class.removeWormhole (http://localhost:7357/assets/vendor.js:90801:12)
                at Class.removeWormhole (http://localhost:7357/assets/vendor.js:91023:19)
        message: >
            Assertion Failed: You attempted to update `nodes` on `<EmberObject:ember910>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

            `nodes` was first used:

            - While rendering:
              application
                tethered-animatable

            Stack trace for the update:
        negative: >
            false
        browser log: |
    ...
```

**Comment by jacobq** [comment]
This is an upstream bug. I was able to work around it using the following [resolution](https://classic.yarnpkg.com/en/docs/package-json#toc-resolutions) in `package.json`:

```
  "resolutions": {
    "liquid-wormhole": "jacobq/liquid-wormhole#32eeeabb2fec5a51fdbffb96214553e5ed4d0016"
  },
```

**Comment by jacobq** [comment]
I think this is taken care of by [v4](https://github.com/yapplabs/ember-modal-dialog/blob/master/CHANGELOG.md#v400-2022-02-09)
