### ISSUE TITLE
Template Deprecations (due to `bind-attr` and `classNameBindings`) with 1.13+.

### ISSUE THREAD

**Issue by rwjblue** [yapplabs/ember-modal-dialog#34]
The [addon/templates/components/modal-dialog.hbs](https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/templates/components/modal-dialog.hbs#L3) is triggering the following deprecations on Canary builds:

```
DEPRECATION: The `bind-attr` helper ('modules/ember-modal-dialog/templates/components/modal-dialog.hbs' @ L3:C11) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/Users/rwjblue/src/work/cardstack/takeoff/bower_components/ember/ember-template-compiler.js:9692:24)
        at /Users/rwjblue/src/work/cardstack/takeoff/bower_components/ember/ember-template-compiler.js:9568:15
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15489:7)
        at visitors.Program (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15499:16)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
        at visitors.BlockStatement (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15510:14)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
DEPRECATION: You're using legacy class binding syntax: classBinding="containerClassNamesString alignmentClass renderInPlaceClass container-class" @ 5:45 in (inline). Please replace with class=""
        at /Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10241:26
        at each (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10308:7)
        at /Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10226:7
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15489:7)
        at visitors.Program (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15499:16)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
        at visitors.BlockStatement (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15510:14)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
```

**Comment by lukemelia** [comment]
@rwjblue what is the best pattern for addons supporting multiple versions of Ember with respect to this kind of thing? Would be have separate versions of the templates and conditionally use the correct one?

**Comment by rwjblue** [comment]
I can see two potential solutions (likely there are more):

1. Maintain two template files, and implement an `treeFor` that returns the right one.
2. Maintain two branches.

Clearly 2 is not great...

**Comment by lukemelia** [comment]
@rwjblue looking into your suggested solution "1" now, and realized that (unless I missed something) I don't know the Ember version an app is using from within the addon.

**Comment by lukemelia** [comment]
@rwjblue Also found that ember-cli was missing the `treeForAddonTemplates` hook, which is where we would need to customize. Added it here: ember-cli/ember-cli#4159

**Comment by lukemelia** [comment]
Working on a fix here: https://github.com/yapplabs/ember-modal-dialog/pull/41
